### ISSUE TITLE
[Question] - Should we realy expect an `UUID` for a wire in schema?

### ISSUE THREAD

**Issue by macielti** [gumberss/PurchaseListinator#70]
Don't we need to receive `UUID`s as `String`?
https://github.com/gumberss/PurchaseListinator/blob/da89092ccbf7c0d2a61749b6eaddf47566e9f1db/src/purchase_listinator/wires/in/purchase_category_events.clj#L4-L8

**Comment by macielti** [comment]
@gumberss

**Comment by gumberss** [comment]
If the wire is for RabbitMQ Events it is not needed because the data is [coerced](https://github.com/gumberss/PurchaseListinator/blob/main/src/purchase_listinator/components/rabbitmq.clj#L35) inside the component if the schema is provided in the [queue definition](https://github.com/gumberss/PurchaseListinator/blob/main/src/purchase_listinator/endpoints/queue/shopping_purchase_list_event_received.clj#L39)
